server:
  port: 8080
  max-http-header-size: 10000000 # this is required to handle the long size JWT
  servlet:
    context-path: /movierama
  compression:
    enabled: true
spring:
  aop:
    proxy-target-class: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_sswJkuXU4
  data:
    web:
      pageable:
        default-page-size: 20
    mongodb:
      uri: mongodb://root:example@localhost:27017/movierama
      username: root
      password: example
      database: movierama
      port: 27017